### ISSUE TITLE
Standardize class of BarcodeID returned by sampspec

### ISSUE THREAD

**Issue by mdodrill-usgs** [jmuehlbauer-usgs/R-packages#19]
sampspec returns a list where multiple elements have the variable BarcodeID.  In some elements (Samples, Missing, SampDel), BarcodeID is a character, in all other elements BarcodeID is a factor.

Doesn't really matter much, but we could standardize these to avoid warnings when joining the data.frames by BarcodeID

**Comment by jmuehlbauer-usgs** [comment]
Ran the following code just now, taking advantage of the fact that `BarcodeID` is always the first column in the resulting list dataframes. Looks like I corrected this issue in some past version update, as all are already factors.

`require(foodbase)`
`t1 <- sampspec(gear = "Drift", stats = TRUE)`
`sapply(sapply(t1, function(x) sapply(x, class)), function(y) y[[1]])`
