### ISSUE TITLE
install_github not working

### ISSUE THREAD

**Issue by jmuehlbauer-usgs** [jmuehlbauer-usgs/R-packages#20]
For some reason the call `install_github(repo='jmuehlbauer-usgs/R-packages',subdir='foodbase')` is not working at the moment. The error text is the following. Might just need to re-build the package in `devtools`?

`Downloading GitHub repo jmuehlbauer-usgs/R-packages@master`
`C:\ArcGIS\gbin\tar.exe: Cannot use compressed or remote archives`
`C:\ArcGIS\gbin\tar.exe: Error is not recoverable: exiting now`
`External tar failed with --force-local, trying without`
`C:\ArcGIS\gbin\tar.exe: Cannot use compressed or remote archives`
`C:\ArcGIS\gbin\tar.exe: Error is not recoverable: exiting now`
`External tar failed with --force-local, trying without`
`Error: Does not appear to be an R package (no DESCRIPTION)`
`In addition: Warning messages:`
`1: In utils::untar(tarfile, ...) :`
`  ‘tar.exe -zxf "C:\Users\JMUEHL~1\AppData\Local\Temp\1\RtmpIhxpbx\file306838604d45.tar.gz" -C` `"C:/Users/JMUEHL~1/AppData/Local/Temp/1/RtmpIhxpbx/remotes3068a7d2b0c"’ returned error code 2`
`2: In system(cmd, intern = TRUE) :`
  `running command 'tar.exe -ztf "C:\Users\JMUEHL~1\AppData\Local\Temp\1\RtmpIhxpbx\file306838604d45.tar.gz"' had status 2`

**Comment by mdodrill-usgs** [comment]
Jeff,  the install from GitHub works fine on my machine (although I get 2 warnings about extended headers).  I'd guess it's a permissions thing on your local machine.

**Comment by jmuehlbauer-usgs** [comment]
It seems that new R installs by DOI, in combination with the latest releases of `devtools`, are doing some weird things with package installs from GitHub. These issues seem to be rectified by including the following lines of code in the User's .Rprofile file (or, alternately, running similar code within the R GUI):
`Sys.setenv("TAR" = "internal")`
`options(download.file.method = "wininet")`
The "extended headers" warning still persists, which is probably something I need to fix eventually in the package Description files. But it doesn't impede the install or functionality of the packages.

**Comment by mdodrill-usgs** [comment]
Awesome, thanks for tracking this down.
