### ISSUE TITLE
'sampspec' warnings when selecting species 

### ISSUE THREAD

**Issue by mdodrill-usgs** [jmuehlbauer-usgs/R-packages#6]
When using 'sampspec' with species = c('taxa1', 'taxa2', ...) function throws warnings:

In if (species == "All" | species == "") { :
  the condition has length > 1 and only the first element will be used

We need to change the logic in the 'if' statement so that when species is a character vector of different taxa, this is handled without warnings.  The function seems to return the correct subset of taxa. 

Mike

**Comment by jmuehlbauer-usgs** [comment]
Fixed if statement logic to address multi-species case. No more warning message.
